// Kitchen email service.
//
// Renders + sends a vendor purchase-order email and writes an audit event
// in either case (success or failure). Reuses the existing nodemailer
// transport from emailService.ts (Gmail SMTP).

import nodemailer from 'nodemailer';
import { prisma } from '../lib/prisma';

interface POForEmail {
    id: string;
    weekStart: Date;
    weekEnd: Date;
    totalAmount: number;
    storeName: string;
    storeAddress: string | null;
    vendorName: string;
    vendorEmail: string;
    items: {
        productName: string;
        qty: number;
        unit: string;
        unitCost: number;
        lineTotal: number;
        caseSize: number | null;
    }[];
}

function createTransporter() {
    const user = process.env.GMAIL_USER;
    const pass = process.env.GMAIL_APP_PASSWORD;
    if (!user || !pass) return null;
    return nodemailer.createTransport({ service: 'gmail', auth: { user, pass } });
}

function renderEmailHtml(po: POForEmail): string {
    const fmtMoney = (n: number) => `$${n.toFixed(2)}`;
    const fmtDate = (d: Date) => new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

    const rows = po.items.map(it => `
        <tr>
            <td style="padding:8px 12px;border-bottom:1px solid #E4E4E7;font-family:Arial,sans-serif;font-size:13px;color:#18181B;">
                ${it.productName}${it.caseSize ? ` <span style="color:#71717A;font-size:11px;">(${it.caseSize}/case)</span>` : ''}
            </td>
            <td style="padding:8px 12px;border-bottom:1px solid #E4E4E7;font-family:Arial,sans-serif;font-size:13px;color:#18181B;text-align:right;font-variant-numeric:tabular-nums;">${it.qty} ${it.unit}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #E4E4E7;font-family:Arial,sans-serif;font-size:13px;color:#52525B;text-align:right;font-variant-numeric:tabular-nums;">${fmtMoney(it.unitCost)}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #E4E4E7;font-family:Arial,sans-serif;font-size:13px;color:#18181B;text-align:right;font-weight:600;font-variant-numeric:tabular-nums;">${fmtMoney(it.lineTotal)}</td>
        </tr>
    `).join('');

    return `
<div style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;padding:24px;background:#FAFAFA;">
    <div style="background:white;border:1px solid #E4E4E7;border-radius:12px;padding:32px;">
        <p style="font-size:11px;color:#4F46E5;letter-spacing:0.12em;text-transform:uppercase;font-weight:600;margin:0 0 4px;">Purchase Order #${po.id.slice(0, 8).toUpperCase()}</p>
        <h2 style="margin:0 0 4px;font-size:22px;color:#18181B;letter-spacing:-0.02em;">Weekly order — ${fmtDate(po.weekStart)} to ${fmtDate(po.weekEnd)}</h2>
        <p style="margin:0 0 24px;color:#52525B;font-size:14px;">From <strong>${po.storeName}</strong>${po.storeAddress ? ` · ${po.storeAddress}` : ''}</p>

        <p style="margin:0 0 16px;color:#27272A;font-size:14px;">Hi ${po.vendorName} team,</p>
        <p style="margin:0 0 24px;color:#27272A;font-size:14px;line-height:1.55;">Please confirm the following order for next week's delivery. Reply to this email with any substitutions, lead-time issues, or invoice questions.</p>

        <table style="width:100%;border-collapse:collapse;border-top:2px solid #18181B;">
            <thead>
                <tr>
                    <th style="padding:10px 12px;text-align:left;font-family:Arial,sans-serif;font-size:11px;color:#71717A;text-transform:uppercase;letter-spacing:0.1em;border-bottom:1px solid #E4E4E7;">Item</th>
                    <th style="padding:10px 12px;text-align:right;font-family:Arial,sans-serif;font-size:11px;color:#71717A;text-transform:uppercase;letter-spacing:0.1em;border-bottom:1px solid #E4E4E7;">Qty</th>
                    <th style="padding:10px 12px;text-align:right;font-family:Arial,sans-serif;font-size:11px;color:#71717A;text-transform:uppercase;letter-spacing:0.1em;border-bottom:1px solid #E4E4E7;">Unit</th>
                    <th style="padding:10px 12px;text-align:right;font-family:Arial,sans-serif;font-size:11px;color:#71717A;text-transform:uppercase;letter-spacing:0.1em;border-bottom:1px solid #E4E4E7;">Total</th>
                </tr>
            </thead>
            <tbody>${rows}</tbody>
            <tfoot>
                <tr>
                    <td colspan="3" style="padding:14px 12px;text-align:right;font-family:Arial,sans-serif;font-size:13px;color:#27272A;font-weight:600;">Order total</td>
                    <td style="padding:14px 12px;text-align:right;font-family:Arial,sans-serif;font-size:18px;color:#18181B;font-weight:700;font-variant-numeric:tabular-nums;letter-spacing:-0.02em;">${fmtMoney(po.totalAmount)}</td>
                </tr>
            </tfoot>
        </table>

        <p style="margin:24px 0 0;color:#52525B;font-size:12px;line-height:1.55;">Generated by Fluxor Kitchen on ${new Date().toLocaleDateString('en-US')}. PO ID: ${po.id}.</p>
    </div>
    <p style="text-align:center;font-size:11px;color:#A1A1AA;margin:16px 0 0;">This is an automated weekly order. Reply to confirm or request changes.</p>
</div>
    `.trim();
}

function renderEmailText(po: POForEmail): string {
    const fmtMoney = (n: number) => `$${n.toFixed(2)}`;
    const lines: string[] = [];
    lines.push(`PURCHASE ORDER #${po.id.slice(0, 8).toUpperCase()}`);
    lines.push(`From: ${po.storeName}${po.storeAddress ? ` (${po.storeAddress})` : ''}`);
    lines.push(`Week: ${new Date(po.weekStart).toDateString()} – ${new Date(po.weekEnd).toDateString()}`);
    lines.push('');
    lines.push('Items:');
    for (const it of po.items) {
        lines.push(`  - ${it.productName}: ${it.qty} ${it.unit} @ ${fmtMoney(it.unitCost)} = ${fmtMoney(it.lineTotal)}`);
    }
    lines.push('');
    lines.push(`TOTAL: ${fmtMoney(po.totalAmount)}`);
    lines.push('');
    lines.push('Reply to confirm or request changes.');
    return lines.join('\n');
}

/**
 * Send a vendor email for a purchase order. Updates PO status + writes an audit event.
 * Returns true if the email was sent, false otherwise.
 */
export async function sendPurchaseOrderEmail(purchaseOrderId: string, actorId = 'system'): Promise<boolean> {
    const po = await prisma.purchaseOrder.findUnique({
        where: { id: purchaseOrderId },
        include: {
            items: true,
            vendor: true,
            store: { select: { name: true, address: true } },
        },
    });

    if (!po) throw new Error(`Purchase order ${purchaseOrderId} not found`);
    if (!po.vendor.contactEmail) {
        await prisma.purchaseOrder.update({
            where: { id: purchaseOrderId },
            data: {
                status: 'FAILED',
                failureReason: 'Vendor has no contactEmail set',
                events: { create: { type: 'FAILED', actorId, payload: 'No vendor email' } },
            },
        });
        return false;
    }

    const transporter = createTransporter();
    if (!transporter) {
        await prisma.purchaseOrder.update({
            where: { id: purchaseOrderId },
            data: {
                status: 'FAILED',
                failureReason: 'GMAIL_USER / GMAIL_APP_PASSWORD not configured',
                events: { create: { type: 'FAILED', actorId, payload: 'Email transport unavailable' } },
            },
        });
        return false;
    }

    const payload: POForEmail = {
        id: po.id,
        weekStart: po.weekStart,
        weekEnd: po.weekEnd,
        totalAmount: po.totalAmount,
        storeName: po.store.name,
        storeAddress: po.store.address,
        vendorName: po.vendor.name,
        vendorEmail: po.vendor.contactEmail,
        items: po.items.map(it => ({
            productName: it.productName,
            qty: it.qty,
            unit: it.unit,
            unitCost: it.unitCost,
            lineTotal: it.lineTotal,
            caseSize: it.caseSize ?? null,
        })),
    };

    try {
        const info = await transporter.sendMail({
            from: `"${po.store.name} via Fluxor" <${process.env.GMAIL_USER}>`,
            to: po.vendor.contactEmail,
            subject: `Weekly order — ${po.store.name} — PO ${po.id.slice(0, 8).toUpperCase()}`,
            html: renderEmailHtml(payload),
            text: renderEmailText(payload),
        });

        await prisma.purchaseOrder.update({
            where: { id: purchaseOrderId },
            data: {
                status: 'SENT',
                emailedAt: new Date(),
                emailedTo: po.vendor.contactEmail,
                emailMessageId: info.messageId,
                events: {
                    create: {
                        type: 'SENT',
                        actorId,
                        payload: JSON.stringify({ to: po.vendor.contactEmail, messageId: info.messageId }),
                    },
                },
            },
        });
        return true;
    } catch (err: any) {
        await prisma.purchaseOrder.update({
            where: { id: purchaseOrderId },
            data: {
                status: 'FAILED',
                failureReason: err.message ?? String(err),
                events: { create: { type: 'FAILED', actorId, payload: err.message ?? String(err) } },
            },
        });
        return false;
    }
}
